##EXPERIMENT DEFINES
DATASET_DIR = '../dataset'
DATASET_SIGMENTATION_DIR = DATASET_DIR + '/dataset_sigmentation'
DATASET_SRC_DIR = DATASET_DIR + '/dataset'
FEATURES_DIR = '../features'
EXPERIMENT_RESULTS_DIR = '../experiment_results'
EXPERIMENT_RESULTS_TEMPLATE = 'experiment_result_template.xlsx'


ATTRIBUTES_ROW = '2'
EXPERIMENT_NUM_COL = 'A'
EXPERIMENTS_FILE = 'experiments.xlsx'
EXPERIMENTS_TAB = 'experiments'

RESULTS_TAB = 'results'
RESULTS_TITLES_ROW = 7
RESULTS_ATTRIBUTE_ROW = 2
RESULTS_SUB_EXPERIMENT_WIDTH = 6
RESULTS_INDEX_OFFSET = 6

